name: parkpal
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^3.1.0
  geocoder: ^0.2.1
  tuple: ^2.0.0
  latlong2: ^0.8.1 
  positioned_tap_detector_2: ^1.0.4
  transparent_image: ^2.0.1
  async: ^2.1.0
  flutter_image: ^3.0.0
  vector_math: ^2.0.0
  proj4dart: ^2.1.0
  meta: ^1.1.0
  collection: ^1.14.0
  http: ^0.13.5
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
